export const glossaryCategories = [
  { id: "all", label: "全部" },
  { id: "calls", label: "规则呼叫" },
  { id: "talk", label: "场上英文" },
  { id: "tactics", label: "战术术语" },
  { id: "signals", label: "官方手势" },
];

export const glossaryEntries = [
  {
    term: "Foul",
    zh: "犯规",
    category: "calls",
    meaning: "发生影响比赛的非轻微身体接触时，由被犯规的队员清楚呼叫“Foul”。",
    tip: "呼叫后先看后续传盘结果，再按连续性规则讨论和处理。",
  },
  {
    term: "Violation",
    zh: "违例",
    category: "calls",
    meaning: "用于不属于身体接触犯规、盯防违规或走步违规的其他规则违反。",
    tip: "说出具体违例名称更容易让所有人理解。",
  },
  {
    term: "Travel",
    zh: "走步",
    category: "calls",
    meaning: "持盘者未正确建立或保持支点、接盘后未尽快减速，或在传盘中移动支点。",
    tip: "任何防守队员都可以呼叫；若传盘未完成，攻防转换通常仍成立。",
  },
  {
    term: "Pick",
    zh: "掩挡",
    category: "calls",
    meaning: "防守者跟随自己盯防的人时，被其他队员阻挡了移动路线。",
    tip: "只有确实影响防守时才呼叫；大声说“Pick”并举起官方手势。",
  },
  {
    term: "Dangerous Play",
    zh: "危险动作",
    category: "calls",
    meaning: "不顾他人安全、带来明显受伤风险的动作；即使尚未发生接触也可以构成犯规。",
    tip: "安全优先，清楚呼叫“Dangerous Play”并立即控制动作。",
  },
  {
    term: "Strip",
    zh: "夺权犯规",
    category: "calls",
    meaning: "接盘者已经建立盘权后，防守者的动作使飞盘脱手。",
    tip: "与尚未完成接盘时的正常防盘不同。",
  },
  {
    term: "Fast Count",
    zh: "读秒过快",
    category: "calls",
    meaning: "防盘者没有以“Stalling”开始、间隔不足一秒，或错误开始、恢复读秒。",
    tip: "属于盯防违规，持盘者应直接呼叫具体名称。",
  },
  {
    term: "Double Team",
    zh: "双人盯防",
    category: "calls",
    meaning: "除合法防盘者外，另一名防守者在不盯防其他进攻者时进入持盘者三米范围。",
    tip: "任何进攻队员都可以呼叫。",
  },
  {
    term: "Disc Space",
    zh: "盘距不足",
    category: "calls",
    meaning: "防盘者身体与持盘者躯干之间小于一个飞盘直径，且并非仅由持盘者动作造成。",
    tip: "呼叫后防盘者应立即修正距离。",
  },
  {
    term: "Straddle",
    zh: "跨站违规",
    category: "calls",
    meaning: "防盘者双脚连线距离持盘者支点小于一个飞盘直径。",
    tip: "与 Disc Space、Wrapping 同属盯防违规。",
  },
  {
    term: "Wrapping",
    zh: "环抱违规",
    category: "calls",
    meaning: "防盘者双手或手臂形成的连线过度环绕持盘者躯干。",
    tip: "呼叫后防盘者应打开站位，恢复合法盘距。",
  },
  {
    term: "Vision Blocking",
    zh: "遮挡视线",
    category: "calls",
    meaning: "防盘者故意用身体部位遮挡持盘者视线。",
    tip: "手臂可以合法防盘，但不能以遮眼为目的。",
  },
  {
    term: "Contact",
    zh: "接触违规",
    category: "calls",
    meaning: "防盘者造成了不构成一般犯规、但应避免的轻微接触。",
    tip: "无争议时比赛不停，读秒重置为 Stalling One。",
  },
  {
    term: "Stall-out",
    zh: "读秒出手超时",
    category: "calls",
    meaning: "防盘者已经开始说出“Ten”而持盘者仍未释放飞盘，盘权转换并停表验盘。",
    tip: "若持盘者认为读秒过快且来不及先呼叫，可对 Stall-out 提出 Contest。",
  },
  {
    term: "Contest",
    zh: "有争议",
    category: "calls",
    meaning: "被呼叫的一方认为呼叫不正确时，明确回应“Contest”。",
    tip: "只说明自己看到的事实，直接相关队员简短讨论。",
  },
  {
    term: "Accepted / Uncontested",
    zh: "接受 / 无争议",
    category: "calls",
    meaning: "被呼叫的一方认可呼叫时，回应“Accepted”或常用的“Uncontested”。",
    tip: "确认处理结果和恢复读秒后再验盘。",
  },
  {
    term: "Retracted",
    zh: "撤回呼叫",
    category: "calls",
    meaning: "呼叫者确认自己的呼叫有误时，说“Retracted”主动撤回。",
    tip: "撤回是飞盘精神的一部分，不需要为了面子坚持错误呼叫。",
  },
  {
    term: "Play On",
    zh: "继续比赛",
    category: "calls",
    meaning: "呼叫方仍获得或保持盘权，且该事件没有影响结果时，尽快说“Play On”。",
    tip: "让队员知道比赛不必停止。",
  },
  {
    term: "Disc In",
    zh: "验盘后恢复",
    category: "calls",
    meaning: "停表后恢复比赛时，附近没有防守者则持盘者触地并可说“Disc In”；盘在地上时由最近防守者呼叫。",
    tip: "有防守者在触及范围内时，应由防守者触盘完成 Check。",
  },
  {
    term: "Injury",
    zh: "受伤暂停",
    category: "calls",
    meaning: "受伤队员或其队友可以呼叫“Injury”停止比赛。",
    tip: "先确保安全，再讨论换人、盘权和恢复位置。",
  },
  {
    term: "Time-out",
    zh: "暂停",
    category: "calls",
    meaning: "拥有盘权的持盘者在合法条件下呼叫“Time-out”。",
    tip: "双手或手与飞盘组成 T 形手势。",
  },
  {
    term: "Brick",
    zh: "砖点",
    category: "calls",
    meaning: "开盘直接出界时，接盘方可以选择在规定的 Brick 点开始进攻。",
    tip: "决定使用 Brick 后应在拿起飞盘前清楚示意。",
  },
  {
    term: "Out / In",
    zh: "出界 / 界内",
    category: "calls",
    meaning: "判断接盘者最后的落地点或飞盘位置在边线外还是场内。",
    tip: "边线本身属于界外；最有视角的队员应帮助判断。",
  },
  {
    term: "Down",
    zh: "飞盘落地",
    category: "calls",
    meaning: "表示传盘在建立盘权前触地，形成攻防转换。",
    tip: "不确定时由有最佳视角的队员沟通，不要隔很远武断呼叫。",
  },
  {
    term: "Goal",
    zh: "得分",
    category: "calls",
    meaning: "进攻队员在进攻得分区内、界内建立飞盘盘权。",
    tip: "确认落点与盘权后，双臂向上示意得分。",
  },

  {
    term: "Up!",
    zh: "盘已出手",
    category: "talk",
    meaning: "有人传出飞盘时大声提醒所有防守队员抬头寻找飞盘。",
    tip: "边线和场上队友都可以及时、响亮地喊。",
  },
  {
    term: "Force Flick / Forehand",
    zh: "逼正手",
    category: "talk",
    meaning: "防盘者封住反手侧，引导持盘者向正手侧传盘。",
    tip: "Flick 与 Forehand 在这里通常指同一种正手传盘。",
  },
  {
    term: "Force Backhand",
    zh: "逼反手",
    category: "talk",
    meaning: "防盘者封住正手侧，引导持盘者向反手侧传盘。",
    tip: "先确认对方是否左手持盘，避免只按左右记忆。",
  },
  {
    term: "Force Home / Away",
    zh: "逼主边 / 客边",
    category: "talk",
    meaning: "用两条边线命名防守方向；Home 通常是本队装备和替补所在边线。",
    tip: "赛前一定先统一哪侧是 Home、哪侧是 Away。",
  },
  {
    term: "No Around!",
    zh: "封外绕",
    category: "talk",
    meaning: "提醒防盘者优先阻止飞盘从身体外侧绕到破防侧。",
    tip: "这是常用边线指令，不是规则呼叫。",
  },
  {
    term: "No Inside!",
    zh: "封内线",
    category: "talk",
    meaning: "提醒防盘者封住靠近身体内侧、穿过中路的破防传盘。",
    tip: "No Around 与 No Inside 的具体优先级由队伍战术决定。",
  },
  {
    term: "No Huck!",
    zh: "防长传",
    category: "talk",
    meaning: "提醒防盘者扩大干扰范围，优先阻止直接打向深区的长传。",
    tip: "不要因此完全放弃既定 Force，听从本队约定。",
  },
  {
    term: "Strike!",
    zh: "防上线 / 直插",
    category: "talk",
    meaning: "常用于提醒防盘者短暂封住 Handler 沿边线向前直插的传盘。",
    tip: "进攻中 Strike 也可指一次快速 Upline 跑位，语境很重要。",
  },
  {
    term: "Switch!",
    zh: "交换盯防",
    category: "talk",
    meaning: "两名防守者交换各自负责的进攻队员，以应对交叉跑位或错位。",
    tip: "呼叫后要指人并确认，避免两个人同时放掉同一名进攻者。",
  },
  {
    term: "Help!",
    zh: "协防",
    category: "talk",
    meaning: "提醒附近队友暂时补位，保护即将出现的空当或深区。",
    tip: "补位后继续沟通谁接管原来的盯防对象。",
  },
  {
    term: "Poach!",
    zh: "漏人 / 防守沉区",
    category: "talk",
    meaning: "可能表示防守者离开直接盯人去保护空间，也可能提醒某名进攻者已经无人盯防。",
    tip: "不同队伍用法差异较大，赛前先统一。",
  },
  {
    term: "Check Feet!",
    zh: "看脚下是否出界",
    category: "talk",
    meaning: "提醒边线附近的接盘者或最佳视角队员确认落点是否界内。",
    tip: "它是信息提醒，不等于正式的 Out 呼叫。",
  },
  {
    term: "Clear!",
    zh: "清空空间",
    category: "talk",
    meaning: "跑位未获得传盘后迅速离开当前通道，为下一名队友创造空间。",
    tip: "跑完一次切入就及时 Clear，避免多人挤在同一区域。",
  },
  {
    term: "Match / Man!",
    zh: "转盯人",
    category: "talk",
    meaning: "提醒全队从区域防守切换为一对一盯防。",
    tip: "所有场上与边线队友应重复呼叫，确保全队收到。",
  },
  {
    term: "Fire!",
    zh: "区域转盯人",
    category: "talk",
    meaning: "许多队伍用“Fire”表示立即从联防切换到盯人。",
    tip: "这是队伍约定用语，并非全球统一；赛前先确认含义。",
  },
  {
    term: "Lefty!",
    zh: "左手持盘提醒",
    category: "talk",
    meaning: "提醒防守队友当前持盘者是左手选手，正反手和 Force 方向需要相应判断。",
    tip: "比机械记忆场地左右更可靠。",
  },

  {
    term: "Pull",
    zh: "开盘",
    category: "tactics",
    meaning: "每一分开始时，防守方从本方得分区向进攻方投出的长传。",
    tip: "开盘前双方举手表示准备就绪。",
  },
  {
    term: "Handler",
    zh: "控盘手",
    category: "tactics",
    meaning: "主要负责后场接应、组织传盘和稳定盘权的进攻队员。",
    tip: "常见任务包括 Dump、Swing 和 Break。",
  },
  {
    term: "Cutter",
    zh: "跑位手",
    category: "tactics",
    meaning: "主要在前场通过跑位创造接盘空间和推进码数的队员。",
    tip: "切入后没有接到盘要及时 Clear。",
  },
  {
    term: "Mark / Marker",
    zh: "防盘 / 防盘者",
    category: "tactics",
    meaning: "直接防守持盘者的人，通过合法站位限制传盘方向并进行 Stall Count。",
    tip: "Mark 是动作或站位，Marker 是执行防盘的人。",
  },
  {
    term: "Open Side / Force Side",
    zh: "开放侧 / 引导侧",
    category: "tactics",
    meaning: "防盘站位主动允许持盘者较容易传向的一侧。",
    tip: "下游防守通常会重点保护这一侧的跑位。",
  },
  {
    term: "Break Side",
    zh: "破防侧",
    category: "tactics",
    meaning: "防盘者试图封住的场地一侧。",
    tip: "成功把盘传到这一侧称为 Break Throw。",
  },
  {
    term: "Dump / Reset",
    zh: "回传 / 重置",
    category: "tactics",
    meaning: "传给持盘者后方或平行位置的队友，重新获得更安全的传盘角度和读秒。",
    tip: "Reset 更强调保持盘权，而不是消极后退。",
  },
  {
    term: "Swing",
    zh: "横传转边",
    category: "tactics",
    meaning: "把飞盘从场地一侧横向转移到另一侧，迫使防守整体移动。",
    tip: "常见组合是 Dump-Swing。",
  },
  {
    term: "Upline",
    zh: "沿线向前",
    category: "tactics",
    meaning: "后场接应队员沿边线或持盘者同侧快速向进攻方向跑位。",
    tip: "也常被称为 Strike cut。",
  },
  {
    term: "Under / In-cut",
    zh: "向盘切入",
    category: "tactics",
    meaning: "从前场向持盘者方向跑回，争取短传推进。",
    tip: "接盘后通常有较好的连续传盘机会。",
  },
  {
    term: "Deep / Away Cut",
    zh: "向深区跑位",
    category: "tactics",
    meaning: "远离持盘者、朝进攻得分区方向冲刺，争取长传。",
    tip: "与 Under 形成一深一浅的空间选择。",
  },
  {
    term: "Huck",
    zh: "长传",
    category: "tactics",
    meaning: "直接跨越较长距离、通常打向深区跑位队员的传盘。",
    tip: "出手前要同时判断风、空间、接盘者和深防位置。",
  },
  {
    term: "Break Throw",
    zh: "破防传盘",
    category: "tactics",
    meaning: "越过防盘者，把飞盘传到 Break Side 的传盘。",
    tip: "常见线路包括 Around 和 Inside。",
  },
  {
    term: "Around",
    zh: "外绕破防",
    category: "tactics",
    meaning: "从防盘者身体外侧绕过的 Break Throw。",
    tip: "通常线路更宽，接盘点靠近破防侧。",
  },
  {
    term: "Inside",
    zh: "内线破防",
    category: "tactics",
    meaning: "从防盘者与开放侧之间的内侧窗口穿过的 Break Throw。",
    tip: "窗口较窄，需要角度、触感与时机。",
  },
  {
    term: "Vertical Stack",
    zh: "纵向 Stack",
    category: "tactics",
    meaning: "跑位队员沿场地纵向排成队列，依次向两侧空间切出。",
    tip: "队列本身要保持间距，把两侧留给切入者。",
  },
  {
    term: "Horizontal Stack",
    zh: "横向 Stack",
    category: "tactics",
    meaning: "跑位队员横向分布在场地宽度上，从不同位置向前或向盘切入。",
    tip: "强调宽度和一对一跑位空间。",
  },
  {
    term: "Iso",
    zh: "单点拉开",
    category: "tactics",
    meaning: "全队主动清出空间，让指定跑位手进行一对一切入。",
    tip: "Iso 是 Isolation 的简称。",
  },
  {
    term: "Zone / Cup",
    zh: "区域防守 / 杯状防守",
    category: "tactics",
    meaning: "防守者保护空间而非始终盯住一人；Cup 是围绕持盘者的常见前线结构。",
    tip: "进攻通常通过耐心 Reset 和 Swing 拉动区域。",
  },
  {
    term: "Layout",
    zh: "飞扑",
    category: "tactics",
    meaning: "离地扑出以完成接盘或防守封堵。",
    tip: "精彩之前先确保落地区域安全，避免危险动作。",
  },
  {
    term: "Turnover",
    zh: "攻防转换",
    category: "tactics",
    meaning: "传盘落地、出界、被拦截或出现指定违规后，另一队获得盘权。",
    tip: "转换发生时立即从进攻思维切换到防守。",
  },

  {
    term: "1 · Foul",
    zh: "犯规手势",
    category: "signals",
    meaning: "一只手臂向前伸直，另一只前臂横向劈过这条直臂。",
    tip: "配合清楚呼叫“Foul”。",
  },
  {
    term: "2 · Violation",
    zh: "违例手势",
    category: "signals",
    meaning: "双手握拳举过头顶，手臂张开形成 V 字。",
    tip: "配合具体违例名称或“Violation”。",
  },
  {
    term: "3 · Goal",
    zh: "得分手势",
    category: "signals",
    meaning: "双臂完全伸直向上举起，掌心相对。",
    tip: "确认界内建立盘权后使用。",
  },
  {
    term: "4 · Contest",
    zh: "有争议手势",
    category: "signals",
    meaning: "双拳在胸前相碰，手背朝外。",
    tip: "表示对呼叫结果有合理异议。",
  },
  {
    term: "5 · Accepted",
    zh: "接受手势",
    category: "signals",
    meaning: "肘部贴近躯干，双前臂向前伸，掌心向上。",
    tip: "表示接受对方呼叫。",
  },
  {
    term: "6 · Retracted",
    zh: "撤回 / 继续手势",
    category: "signals",
    meaning: "双臂向下伸在身体前方，做交叉扫开的动作。",
    tip: "表示撤回呼叫，或配合 Play On 传达继续比赛。",
  },
  {
    term: "7 · In / Out",
    zh: "界内 / 界外手势",
    category: "signals",
    meaning: "单臂伸直、手掌平直；指向场内表示 In，指向场外表示 Out。",
    tip: "也可指向得分区外表示未得分。",
  },
  {
    term: "8 · Disc Down",
    zh: "飞盘落地手势",
    category: "signals",
    meaning: "手臂伸直，以约 45 度向下指，食指指向地面。",
    tip: "表示飞盘触地、未完成接盘。",
  },
  {
    term: "9 · Disc Up",
    zh: "飞盘未落地手势",
    category: "signals",
    meaning: "肘部向下、前臂竖直，食指向上。",
    tip: "表示飞盘在触地前已被控制。",
  },
  {
    term: "10 · Pick",
    zh: "掩挡手势",
    category: "signals",
    meaning: "抬起双臂并弯曲肘部，两只拳头朝向头部。",
    tip: "配合大声呼叫“Pick”。",
  },
  {
    term: "11 · Travel",
    zh: "走步手势",
    category: "signals",
    meaning: "双手握拳，在身体前方让手腕沿竖直圆周互相绕转。",
    tip: "配合呼叫“Travel”。",
  },
  {
    term: "12 · Marking Infraction",
    zh: "盯防违规手势",
    category: "signals",
    meaning: "双臂向身体两侧伸出，掌心朝前。",
    tip: "适用于 Fast Count、Disc Space、Double Team、Wrapping 等。",
  },
  {
    term: "13 · Turnover",
    zh: "攻防转换手势",
    category: "signals",
    meaning: "右臂伸在身体前方，先掌心向上，再翻转为掌心向下。",
    tip: "表示盘权转移到另一队。",
  },
  {
    term: "14 · Timing Violation",
    zh: "时间违规手势",
    category: "signals",
    meaning: "用张开的手掌轻拍头顶。",
    tip: "用于 Stall-out 等时间违规。",
  },
  {
    term: "15 · Offside / False Start",
    zh: "越位 / 抢跑手势",
    category: "signals",
    meaning: "双臂在头顶交叉成 X，双手握拳。",
    tip: "用于开盘前队员提前越过得分线等情况。",
  },
  {
    term: "16 · Time-out",
    zh: "暂停手势",
    category: "signals",
    meaning: "双手组成 T 字，或用一只手与飞盘组成 T 字。",
    tip: "配合呼叫“Time-out”。",
  },
  {
    term: "17 · Spirit Stoppage",
    zh: "飞盘精神暂停手势",
    category: "signals",
    meaning: "双手组成倒置的 T 字。",
    tip: "用于处理影响飞盘精神的持续问题。",
  },
  {
    term: "18 · Stoppage",
    zh: "受伤 / 技术暂停手势",
    category: "signals",
    meaning: "双手相扣举过头顶，手臂弯曲。",
    tip: "用于 Injury 或 Technical stoppage。",
  },
  {
    term: "19 · Male Matching",
    zh: "男性匹配比例手势",
    category: "signals",
    meaning: "双手置于脑后呈杯状，肘部向两侧展开。",
    tip: "用于混合组别回合开始前的性别比例沟通。",
  },
  {
    term: "20 · Female Matching",
    zh: "女性匹配比例手势",
    category: "signals",
    meaning: "双臂向身体两侧伸直，双手握拳。",
    tip: "用于混合组别回合开始前的性别比例沟通。",
  },
  {
    term: "21 · Play Has Stopped",
    zh: "比赛已停止手势",
    category: "signals",
    meaning: "双臂伸直举过头顶并交叉挥动。",
    tip: "帮助远处队员及时知道停表。",
  },
  {
    term: "22 · Who Made the Call",
    zh: "哪一队呼叫手势",
    category: "signals",
    meaning: "双臂伸直，指向作出呼叫的队伍所防守的得分区。",
    tip: "用于向记分台或远处队员说明呼叫方。",
  },
  {
    term: "23 · Did Not Affect",
    zh: "未影响比赛手势",
    category: "signals",
    meaning: "一只张开的手举过头顶，前后扫动。",
    tip: "表示该事件没有影响比赛结果，结果可以成立。",
  },
  {
    term: "24 · Match Point",
    zh: "赛点手势",
    category: "signals",
    meaning: "双臂一起指向左上方，掌心向下。",
    tip: "表示下一分可能决定比赛胜负。",
  },
];
